magnetism:
  name: "Magnetism" # Name of the enchantment
  activated: true # true or false

smelting:
  name: "Smelting"
  activated: true

replanting:
  name: "Replanting"
  activated: true

treecutter:
  name: "Tree Cutter"
  activated: true
  number_of_logs_to_cut: 5

lore: "top" # top or bottom