name: TeaEnchants
version: '1.0-SNAPSHOT'
main: com.thibault_lombart.teaEnchants.TeaEnchants
api-version: '1.21'
commands:
  TeaEnchants:
    description: Apply a custom enchant.
    usage: /<command> <enchantment>
    permission: teaenchants.teaenchants
    permission-message: You don't have the permission to use this command.
  TeaEnchantsBook:
    description: Give an enchanted book to the player selected.
    usage: /<command> <player> <enchantment>
    permission: teaenchants.teaenchantsbook
    permission-message: You don't have the permission to use this command.
  TeaEnchantsReload:
    description: Reload the plugin.
    usage: /<command>
    permission: teaenchants.teaenchantsreload
    permission-message: You don't have the permission to use this command.
permissions:
  teaenchants.teaenchants:
    description: To use the command TeaEnchants
    default: op
  teaenchants.teaenchantsbook:
    description: To use the command TeaEnchantsBook
    default: op
  teaenchants.teaenchantsreload:
    description: To use the command TeaEnchantsReload
    default: op